[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy-policy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/works"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/company"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/voices"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/index.html"
  status = 200
